"""Work checklists for the LaDoger-approved US-PD-only composers (depth run 1, 2026-10-10).

Single source of truth for docs/catalogues/<slug>.csv (regenerate with
scripts/bulk/catalogue_report.py) and for the importer
(scripts/bulk/import_depth_us_pd.py), which only imports rows whose status is
``in-scope`` (verified published <= 1930).

Row = (cat_no, title, pub_year, status, regex, note)

* cat_no   : Marnat M. (Ravel), Op./TrV (R. Strauss), Op. (Elgar, Rachmaninoff), H. (Holst)
* pub_year : first-publication year (IMSLP / Wikipedia work lists). None = unknown.
* status   : in-scope | excluded-disputed | excluded-post1930 | excluded-unpublished |
             unverified-pub (publication year not confirmed: not imported)
* regex    : matched (case/accent-insensitive, punctuation -> space) against
             "title song_name movement" of a candidate source row.
Checklists list the principal works; they are not exhaustive TrV / H. catalogues
(noted per composer in COMPOSERS[...]["scope_note"]).
"""

IN, DISP, POST, UNPUB, UNV = (
    "in-scope", "excluded-disputed", "excluded-post1930", "excluded-unpublished", "unverified-pub",
)

RAVEL = [
    # --- Piano
    ("M.7", "Menuet antique", 1898, IN, r"menuet antique", "Enoch 1898; orchestration M.7a 1929"),
    ("M.19", "Pavane pour une infante défunte", 1900, IN, r"pavane (pour une infante|for a dead princess|for trombone|pour)|infante defunte", "Demets 1900; orch. M.19a 1910"),
    ("M.30", "Jeux d'eau", 1902, IN, r"jeux d eau", "Demets 1902"),
    ("M.40", "Sonatine", 1905, IN, r"sonatine", "Durand 1905"),
    ("M.43.1", "Miroirs: Noctuelles", 1906, IN, r"noctuelles", "Miroirs, Calmette/Eschig 1906"),
    ("M.43.2", "Miroirs: Oiseaux tristes", 1906, IN, r"oiseaux tristes", ""),
    ("M.43.3", "Miroirs: Une barque sur l'océan", 1906, IN, r"barque sur l ocean", "orch. M.43a 1906/1926"),
    ("M.43.4", "Miroirs: Alborada del gracioso", 1906, IN, r"alborada", "orch. M.43c 1918, Durand 1919"),
    ("M.43.5", "Miroirs: La vallée des cloches", 1906, IN, r"vallee des cloches", ""),
    ("M.55.1", "Gaspard de la nuit: Ondine", 1909, IN, r"ondine", "Durand 1909"),
    ("M.55.2", "Gaspard de la nuit: Le gibet", 1909, IN, r"le gibet|gibet", ""),
    ("M.55.3", "Gaspard de la nuit: Scarbo", 1909, IN, r"scarbo", ""),
    ("M.55", "Gaspard de la nuit (complete)", 1909, IN, r"gaspard de la nuit", "Matches whole-cycle files"),
    ("M.58", "Menuet sur le nom d'Haydn", 1910, IN, r"menuet sur le nom d haydn", "Revue musicale S.I.M. 1910"),
    ("M.60", "Ma mère l'Oye (piano duet)", 1910, IN, r"ma m.re l oye|mother goose|petit poucet|laideronnette|jardin f.erique|belle et de la bete|pavane de la belle", "Durand 1910; ballet M.62 1912, suite orch. M.60a 1911"),
    ("M.61", "Valses nobles et sentimentales", 1911, IN, r"valses nobles", "Durand 1911"),
    ("M.63", "À la manière de… (Borodine, Chabrier)", 1913, IN, r"a la maniere de|manière de", "Revue musicale 1913"),
    ("M.65", "Prélude", 1913, IN, r"^prelude( m ravel)? *( prelude)?$|prelude m ravel|^prelude \(m ravel\)", "Durand 1913 (Conservatoire sight-reading)"),
    ("M.68", "Le Tombeau de Couperin", 1918, IN, r"tombeau de couperin|menuet no 5 from le tombeau", "Durand 1918; orch. M.68a 1919"),
    ("M.72", "La Valse", 1921, IN, r"la valse", "Durand 1921 (piano solo M.72b 1920)"),
    ("M.70", "Frontispice", 1919, IN, r"frontispice", ""),
    # --- Orchestra
    ("M.54", "Rapsodie espagnole", 1908, IN, r"rapsodie espagnole", "Durand 1908"),
    ("M.57", "Daphnis et Chloé", 1913, IN, r"daphnis", "Piano score 1911, orchestral 1913; Suites 1/2 M.57a/b"),
    ("M.A24", "Pictures at an Exhibition (orch. Ravel)", 1929, IN, r"pictures at an exhibition|tableaux d une exposition|bydlo|vecchio castello|grande porte de kiev|ballet des poussins|catacombae|cabane sur des pattes|samuel goldberg|con mortuis|promenade|promendade", "Éditions russes de musique 1929; Mussorgsky d.1881 so the underlying work is PD everywhere, Ravel's orchestration is US-PD-only"),
    ("M.A25", "Debussy: Sarabande (orch. Ravel)", 1923, IN, r"sarabande.*(ravel|orch)", "Durand 1923"),
    ("M.A26", "Debussy: Danse (Tarantelle styrienne) (orch. Ravel)", 1923, IN, r"tarantelle styrienne", "Durand 1923"),
    ("M.52", "L'Heure espagnole", 1908, IN, r"heure espagnole", "Vocal score Durand 1908"),
    ("M.71", "L'Enfant et les sortilèges", 1925, IN, r"enfant et les sortileges", "Vocal score Durand 1925"),
    ("M.80", "Fanfare for L'éventail de Jeanne", 1929, IN, r"eventail de jeanne|fanfare", "Heugel 1929"),
    # --- Chamber
    ("M.35", "String Quartet in F", 1910, IN, r"string quartet in f", "Durand 1910"),
    ("M.46", "Introduction et Allegro", 1906, IN, r"introduction (et|and) allegro", "Durand 1906"),
    ("M.67", "Piano Trio in A minor", 1915, IN, r"piano trio|trio in a", "Durand 1915"),
    ("M.73", "Sonata for Violin and Cello", 1922, IN, r"sonate? for violin and cello|violin and cello", "Durand 1922"),
    ("M.74", "Berceuse sur le nom de Gabriel Fauré", 1922, IN, r"berceuse sur le nom", "Revue musicale 1922"),
    ("M.76", "Tzigane", 1924, IN, r"tzigane", "Durand 1924; orch. M.76a 1924"),
    ("M.77", "Violin Sonata No. 2", 1927, IN, r"violin sonata|sonate for violin and piano", "Durand 1927"),
    # --- Voice
    ("M.41", "Shéhérazade (songs)", 1904, IN, r"sheherazade|asie|flute enchantee|l indifferent", "Jobert 1904"),
    ("M.50", "Histoires naturelles", 1907, IN, r"histoires naturelles|le paon|le grillon|le cygne|martin.pecheur|la pintade", "Durand 1907"),
    ("M.51", "Vocalise-étude / Pièce en forme de habanera", 1907, IN, r"forme de habanera|vocalise", "Leduc 1907"),
    ("M.64", "Trois poèmes de Stéphane Mallarmé", 1914, IN, r"mallarme|soupir|placet futile|surgi de la croupe", "Durand 1914"),
    ("M.69", "Trois chansons", 1916, IN, r"trois chansons|nicolette|beaux oiseaux du paradis|^ronde|ronde maurice", "Durand 1916"),
    ("M.75", "Ronsard à son âme", 1924, IN, r"ronsard", "Revue musicale 1924"),
    ("M.78", "Chansons madécasses", 1926, IN, r"chansons madecasses|aoua|nahandove|il est doux", "Durand 1926"),
    ("M.79", "Rêves", 1927, IN, r"^reves|reves maurice|^reves$", "1927"),
    ("M.A4-11", "Cinq mélodies populaires grecques", 1906, IN, r"melodies populaires grecques|melodies grexques|quel galant|cueilleuses|la bas vers l eglise|tout gai|chanson de la mariee", "Durand 1906"),
    ("M.A17", "Chants populaires", 1910, IN, r"chants populaires|chanson (espagnole|francaise|italienne|hebraique|russe|ecossaise|flamande)", "Chanson espagnole/française/italienne/hébraïque, 1910"),
    ("M.A22", "Deux mélodies hébraïques", 1915, IN, r"kaddisch|kaddish|enigme eternelle|melodies hebraiques", "Durand 1915"),
    # --- Explicit exclusions
    ("M.81", "Boléro", 1929, DISP, r"bolero", "Boléro excluded: disputed (LaDoger). Never import."),
    ("M.82", "Piano Concerto for the Left Hand in D", 1931, POST, r"left hand", "Published 1931"),
    ("M.83", "Piano Concerto in G", 1932, DISP, r"piano concerto in g|concerto in g", "Published 1932; excluded by LaDoger"),
    ("M.84", "Don Quichotte à Dulcinée", 1934, DISP, r"don quichotte", "Composed 1932-33; excluded by LaDoger"),
    ("M.85", "Morgiane", None, POST, r"morgiane", "Unrealised sketches"),
    ("M.86", "Jeanne d'Arc", None, POST, r"jeanne d arc", "Unrealised"),
    ("M.1-3", "Piano Sonata; Grieg and Schumann Variations", None, UNPUB, r"", "Juvenilia, unpublished (first published 1975+)"),
    ("M.4", "Ballade de la reine morte d'aimer", None, UNPUB, r"reine morte d aimer", "Unpublished until 1975"),
    ("M.5", "Sérénade grotesque", None, UNPUB, r"serenade grotesque", "Published 1975"),
    ("M.6", "Un grand sommeil noir", None, UNV, r"grand sommeil noir", "Pub. date not confirmed"),
    ("M.8", "Habanera (Sites auriculaires)", None, UNV, r"^habanera$", "Pub. date not confirmed"),
    ("M.9", "Sainte", None, UNV, r"^sainte", "Pub. date not confirmed"),
    ("M.10", "D'Anne jouant de l'espinette", None, UNV, r"espinette", "Pub. date not confirmed"),
    ("M.11", "La Parade", None, UNPUB, r"la parade", "Unpublished"),
    ("M.12", "Violin Sonata (No. 1, posthumous)", None, UNPUB, r"", "Published 1975"),
    ("M.13", "Entre cloches", None, UNV, r"entre cloches", "Pub. date not confirmed"),
    ("M.14", "Valse in D", None, UNPUB, r"", "Unpublished"),
    ("M.15", "Chanson du rouet", None, UNPUB, r"chanson du rouet", "Unpublished"),
    ("M.16", "Si morne!", None, UNV, r"si morne", "Pub. date not confirmed"),
    ("M.17", "Shéhérazade, ouverture de féerie", None, UNPUB, r"ouverture de feerie", "Published 1975"),
    ("M.18", "Olympia", None, UNPUB, r"olympia", "Unfinished"),
    ("M.20-44", "Conservatoire fugues (M.20, 23, 24, 26, 27, 32, 36, 44)", None, UNPUB, r"fugue", "Unpublished exercises"),
    ("M.21", "D'Anne qui me jecta de la neige", None, UNV, r"jecta de la neige", "Pub. date not confirmed"),
    ("M.22-38", "Prix de Rome cantatas (Callirhoé, Myrrha, Alcyone, Alyssa, ...)", None, UNPUB, r"callirhoe|myrrha|alcyone|alyssa|semiramis|les bayadere", "Unpublished competition cantatas"),
    ("M.39", "Manteau de fleurs", None, UNV, r"manteau de fleurs", "Pub. date not confirmed"),
    ("M.42", "Menuet in C♯ minor", None, UNPUB, r"", "Unpublished"),
    ("M.47", "Noël des jouets", None, UNV, r"noel des jouets", "Pub. date not confirmed"),
    ("M.48", "Les grands vents venus d'outre-mer", None, UNV, r"grands vents", "Pub. date not confirmed"),
    ("M.49", "La cloche engloutie", None, UNPUB, r"cloche engloutie", "Unfinished opera, sketches only"),
    ("M.53", "Sur l'herbe", None, UNV, r"sur l herbe", "Pub. date not confirmed"),
    ("M.59", "Saint François d'Assise", None, UNPUB, r"saint francois", "Unpublished"),
    ("M.66", "Zaspiak-Bat", None, UNPUB, r"zaspiak", "Unfinished, unpublished"),
]

STRAUSS = [
    ("Op.4 / TrV 132", "Suite in B♭ for 13 winds", 1885, IN, r"suite (in b|for wind)", ""),
    ("Op.7 / TrV 106", "Serenade in E♭ for 13 winds", 1882, IN, r"serenade.*(winds|e flat)", ""),
    ("Op.8 / TrV 110", "Violin Concerto in D minor", 1882, IN, r"violin concerto", ""),
    ("Op.11 / TrV 117", "Horn Concerto No. 1 in E♭", 1883, IN, r"horn concerto", "Aibl 1883"),
    ("Op.10 / TrV 141", "Acht Gedichte: Zueignung / Die Nacht / Allerseelen", 1885, IN, r"zueignung|allerseelen|die nacht|acht gedichte", "Op.10 Nos. 1, 3, 8"),
    ("Op.12 / TrV 126", "Symphony No. 2 in F minor", 1887, IN, r"symphony (no )?2|symphony in f minor", ""),
    ("Op.16 / TrV 147", "Aus Italien", 1887, IN, r"aus italien", ""),
    ("Op.18 / TrV 151", "Violin Sonata in E♭", 1888, IN, r"violin sonata", "Includes the Improvisation movement"),
    ("TrV 145", "Burleske in D minor", 1894, IN, r"burleske", "Pub. 1894 (Jos. Aibl); Wikipedia dates composition 1886"),
    ("Op.20 / TrV 156", "Don Juan", 1890, IN, r"don juan", "Leuckart 1890"),
    ("Op.23 / TrV 163", "Macbeth", 1891, IN, r"macbeth", ""),
    ("Op.24 / TrV 158", "Tod und Verklärung", 1891, IN, r"tod und verkl|death (and|&) transfiguration", "Aibl 1891"),
    ("Op.27 / TrV 170", "Vier Lieder: Ruhe meine Seele! / Cäcilie / Heimliche Aufforderung / Morgen!", 1894, IN, r"ruhe meine seele|cacilie|cecilie|heimliche aufforderung|morgen|4 lieder op 27|vier lieder", "Joh. André 1894"),
    ("Op.28 / TrV 171", "Till Eulenspiegels lustige Streiche", 1895, IN, r"till eulenspiegel", "Aibl 1895"),
    ("Op.30 / TrV 176", "Also sprach Zarathustra", 1896, IN, r"zarathustra", "Aibl 1896"),
    ("Op.35 / TrV 184", "Don Quixote", 1898, IN, r"don quixote|don quichotte", "Leuckart 1898"),
    ("Op.40 / TrV 190", "Ein Heldenleben", 1899, IN, r"heldenleben", "Leuckart 1899"),
    ("Op.41 / TrV 195", "Fünf Lieder: Wiegenlied", 1899, IN, r"wiegenlied", "Op.41 No.1 (1899)"),
    ("Op.49 / TrV 204", "Acht Lieder: Waldseligkeit", 1901, IN, r"waldseligkeit", ""),
    ("Op.53 / TrV 209", "Symphonia domestica", 1904, IN, r"symphonia domestica|sinfonia domestica", "Fürstner 1904"),
    ("Op.54 / TrV 215", "Salome", 1905, IN, r"salome", "Fürstner 1905 (incl. Dance of the Seven Veils)"),
    ("Op.58 / TrV 223", "Elektra", 1908, IN, r"elektra", "Fürstner 1908"),
    ("Op.59 / TrV 227", "Der Rosenkavalier", 1911, IN, r"rosenkavalier", "Fürstner 1910-11; Waltz Sequences later"),
    ("Op.60 / TrV 228", "Ariadne auf Naxos / Le Bourgeois gentilhomme", 1912, IN, r"ariadne|bourgeois gentilhomme", "Fürstner 1912; Bourgeois gentilhomme suite 1920"),
    ("Op.63 / TrV 231", "Josephs Legende", 1914, IN, r"josephs legende|legend of joseph", ""),
    ("Op.64 / TrV 233", "Eine Alpensinfonie", 1915, IN, r"alpensinfonie|alpine symphony", "Leuckart 1915"),
    ("Op.65 / TrV 234", "Die Frau ohne Schatten", 1919, IN, r"frau ohne schatten", "Fürstner 1919"),
    ("Op.72 / TrV 246", "Intermezzo", 1924, IN, r"^intermezzo", "Fürstner 1924"),
    ("Op.75 / TrV 255", "Die ägyptische Helena", 1928, IN, r"agyptische helena|egyptian helen", "Fürstner 1928"),
    ("Op.6 / TrV 115", "Cello Sonata in F", 1883, IN, r"cello sonata", ""),
    ("Op.13 / TrV 137", "Piano Quartet in C minor", 1885, IN, r"piano quartet", ""),
    ("Op.79 / TrV 263", "Arabella", 1933, POST, r"arabella", "Published 1933"),
    ("Op.81 / TrV 271", "Friedenstag", 1938, POST, r"friedenstag", ""),
    ("TrV 290", "Metamorphosen", 1946, POST, r"metamorphosen", "Composed 1945"),
    ("TrV 292", "Oboe Concerto", 1948, POST, r"oboe concerto", "Composed 1945"),
    ("TrV 283", "Horn Concerto No. 2", 1942, POST, r"horn concerto no 2|horn concerto no\. 2", "Composed 1942"),
    ("TrV 297", "Vier letzte Lieder", 1950, POST, r"vier letzte|four last", "Published 1950"),
    ("Op.85 / TrV 279", "Capriccio", 1942, POST, r"capriccio", ""),
    ("Op.82 / TrV 272", "Daphne", 1938, POST, r"daphne", ""),
]

ELGAR = [
    ("Op.12", "Salut d'amour (Liebesgruss)", 1889, IN, r"salut d amour|liebesgruss|love s greeting", "Schott 1889"),
    ("Op.15 No.1/2", "Chanson de nuit / Chanson de matin", 1901, IN, r"chanson de (nuit|matin)", "Pub. 1901 (Novello/Schott)"),
    ("Op.19", "Froissart (concert overture)", 1890, IN, r"froissart", ""),
    ("Op.20", "Serenade for Strings in E minor", 1893, IN, r"serenade (for strings|in e)", ""),
    ("Op.27", "Three Bavarian Dances", 1897, IN, r"bavarian (dances|highlands)", ""),
    ("Op.30", "Scenes from the Saga of King Olaf", 1896, IN, r"king olaf|as torrents in summer", "Includes 'As torrents in summer'"),
    ("Op.32", "Sea Pictures", 1899, IN, r"sea pictures|where corals lie|sabbath morning at sea|in haven", ""),
    ("Op.36", "Variations on an Original Theme 'Enigma'", 1899, IN, r"enigma|nimrod|lux aeterna", "Novello 1899"),
    ("Op.38", "The Dream of Gerontius", 1900, IN, r"gerontius", ""),
    ("Op.39 No.1", "Pomp and Circumstance March No. 1 in D", 1901, IN, r"pomp and circumstance (march )?(no )?1|land of hope and glory", "Boosey 1901"),
    ("Op.39 No.2", "Pomp and Circumstance March No. 2 in A minor", 1901, IN, r"pomp and circumstance (march )?(no )?2", ""),
    ("Op.39 No.3", "Pomp and Circumstance March No. 3 in C minor", 1905, IN, r"pomp and circumstance (march )?(no )?3", ""),
    ("Op.39 No.4", "Pomp and Circumstance March No. 4 in G", 1907, IN, r"pomp and circumstance (march )?(no )?4", ""),
    ("Op.39 No.5", "Pomp and Circumstance March No. 5 in C", 1930, UNV, r"pomp and circumstance (march )?(no )?5", "Pub. year 1930 or 1931 not confirmed"),
    ("Op.40", "Cockaigne (In London Town)", 1901, IN, r"cockaigne", ""),
    ("Op.41", "In the South (Alassio)", 1904, IN, r"in the south|alassio", ""),
    ("Op.42", "Grania and Diarmid", 1902, IN, r"grania and diarmid|there are seven that pull", ""),
    ("Op.44", "Coronation Ode", 1902, IN, r"coronation ode", "Land of Hope and Glory finale"),
    ("Op.47", "Introduction and Allegro for Strings", 1905, IN, r"introduction (and|et) allegro", "Novello 1905"),
    ("Op.49", "The Apostles", 1903, IN, r"the apostles", ""),
    ("Op.50", "The Kingdom", 1906, IN, r"the kingdom", ""),
    ("Op.53 No.1", "There is sweet music", 1908, IN, r"there is sweet music", "Part songs from the Greek Anthology"),
    ("Op.55", "Symphony No. 1 in A♭", 1908, IN, r"symphony (no )?1|first symphony", "Novello 1908"),
    ("Op.58", "Elegy for strings", 1909, IN, r"elegy", ""),
    ("Op.61", "Violin Concerto in B minor", 1910, IN, r"violin concerto", "Novello 1910"),
    ("Op.63", "Symphony No. 2 in E♭", 1911, IN, r"symphony (no )?2|second symphony", "Novello 1911"),
    ("Op.64", "Coronation March", 1911, IN, r"coronation march", ""),
    ("Op.68", "Falstaff (symphonic study)", 1913, IN, r"falstaff", ""),
    ("Op.70", "Sospiri", 1914, IN, r"sospiri", ""),
    ("Op.73 No.2", "Evening Scene", 1906, IN, r"evening scene|sheep bell tolleth", "Op.73 part songs"),
    ("Op.82", "Violin Sonata in E minor", 1919, IN, r"violin sonata", ""),
    ("Op.83", "String Quartet in E minor", 1919, IN, r"string quartet", "Novello 1919"),
    ("Op.84", "Piano Quintet in A minor", 1919, IN, r"piano quintet", ""),
    ("Op.85", "Cello Concerto in E minor", 1919, IN, r"cello concerto", "Novello 1919/1920"),
    ("Op.1a / 1b", "The Wand of Youth Suites 1 & 2", 1907, IN, r"wand of youth", ""),
    ("Op.60", "Two Songs (The Torch / The River)", 1909, IN, r"the torch|the river", "Op.60"),
    ("no Op.", "Ave maris stella", 1900, UNV, r"ave maris stella", "Pub. date not confirmed"),
    ("no Op.", "Weary Wind of the West", 1903, UNV, r"weary wind of the west", "Pub. date not confirmed"),
    ("no Op.", "Nursery Suite", 1931, POST, r"nursery suite", "Published 1931"),
    ("Op.87", "Severn Suite", 1930, UNV, r"severn suite", "Brass band 1930; orchestral 1930s"),
    ("no Op.", "Symphony No. 3 (sketches, Payne)", 1998, POST, r"symphony (no )?3", "Elaborated 1998"),
]

HOLST = [
    ("Op.32 / H.125", "The Planets", 1921, IN, r"the planets|mars|venus|mercury|jupiter|saturn|uranus|neptune", "Goodwin & Tabb 1921; Jupiter hymn tune 'Thaxted' from this"),
    ("Op.29 No.2 / H.118", "St Paul's Suite", 1922, IN, r"st paul s suite|fantasia on the dargason|dargason", ""),
    ("Op.28 No.1 / H.105", "First Suite in E♭ for military band", 1921, IN, r"first suite", ""),
    ("Op.28 No.2 / H.106", "Second Suite in F for military band", 1922, IN, r"second suite", ""),
    ("Op.29 No.1 / H.107", "Beni Mora", 1921, IN, r"beni mora", ""),
    ("Op.37 / H.140", "The Hymn of Jesus", 1920, IN, r"hymn of jesus", ""),
    ("Op.47 / H.172", "Egdon Heath", 1928, IN, r"egdon heath", ""),
    ("Op.40 No.2 / H.152", "Fugal Concerto", 1923, IN, r"fugal concerto", ""),
    ("Op.40 No.1 / H.151", "A Fugal Overture", 1922, IN, r"fugal overture", ""),
    ("Op.33 / H.126", "A Japanese Suite", 1922, IN, r"japanese suite", ""),
    ("Op.52 / H.178", "Hammersmith", 1930, UNV, r"hammersmith", "Published 1930/31, not confirmed"),
    ("Op.21 No.2 / H.87", "A Somerset Rhapsody", 1910, IN, r"somerset rhapsody", ""),
    ("no Op.", "In the Bleak Midwinter (Cranham)", 1906, IN, r"bleak midwinter|cranham", "English Hymnal 1906"),
    ("H.148", "I Vow to Thee, My Country (Thaxted)", 1921, IN, r"i vow to thee|thaxted", "Tune 1921; hymn 1925"),
    ("Op.25 / H.96", "Savitri", 1923, IN, r"savitri", ""),
    ("Op.38 / H.144", "Ode to Death", 1922, IN, r"ode to death", ""),
    ("Op.24 / H.90", "Hymns from the Rig Veda (Hymn to Indra)", 1911, IN, r"hymn to indra|rig veda", ""),
    ("Op.39 / H.150", "The Perfect Fool", 1923, IN, r"perfect fool", ""),
    ("no Op.", "Personent hodie (arr.)", 1928, UNV, r"personent hodie", "Arrangement of 16th-c. tune (Piae Cantiones)"),
    ("H.190", "Brook Green Suite", 1934, POST, r"brook green", "Published 1934"),
    ]

RACHMANINOFF = [
    ("Op.1", "Piano Concerto No. 1 in F♯ minor", 1892, IN, r"piano concerto (no )?1|concerto no 1", "1892 / rev. 1917 (pub. 1917)"),
    ("Op.3", "Morceaux de fantaisie (incl. Prélude in C♯ minor)", 1892, IN, r"morceaux de fantaisie|prelude in c.*minor|elegie|polichinelle|serenade|melodie", "Gutheil 1893"),
    ("Op.5", "Fantaisie-tableaux (Suite No. 1)", 1894, IN, r"fantaisie tableaux|fantasie tableaux|suite (no )?1", ""),
    ("Op.16", "Moments musicaux", 1897, IN, r"moment(s)? musica", "Gutheil 1897"),
    ("Op.18", "Piano Concerto No. 2 in C minor", 1901, IN, r"piano concerto (no )?2|concerto no 2", "Gutheil 1901"),
    ("Op.19", "Cello Sonata in G minor", 1901, IN, r"cello sonata", ""),
    ("Op.22", "Variations on a Theme of Chopin", 1903, IN, r"theme of chopin|chopin variations", ""),
    ("Op.23", "Ten Preludes", 1903, IN, r"10 preludes|ten preludes|prelude in (g|d|b|f|e|c)|prelude (op )?23", "Gutheil 1904"),
    ("Op.27", "Symphony No. 2 in E minor", 1908, IN, r"symphony (no )?2", ""),
    ("Op.28", "Piano Sonata No. 1 in D minor", 1908, IN, r"piano sonata (no )?1", ""),
    ("Op.29", "The Isle of the Dead", 1909, IN, r"isle of the dead|toteninsel", ""),
    ("Op.30", "Piano Concerto No. 3 in D minor", 1910, IN, r"piano concerto (no )?3|concerto no 3", "Gutheil 1910"),
    ("Op.31", "Liturgy of St. John Chrysostom", 1910, IN, r"liturgy of st|cherubic hymn|chrysostom", ""),
    ("Op.32", "Thirteen Preludes", 1911, IN, r"13 preludes|thirteen preludes", ""),
    ("Op.33", "Études-tableaux", 1911, IN, r"etudes? tableaux.*(33)|etudes tableaux op 33", ""),
    ("Op.34 No.14", "Vocalise", 1913, IN, r"vocalise", "Gutheil 1913"),
    ("Op.35", "The Bells", 1913, IN, r"the bells|kolokola", ""),
    ("Op.36", "Piano Sonata No. 2 in B♭ minor (1913 / 1931 versions)", 1913, UNV, r"piano sonata (no )?2", "Edition (1913 vs revised 1931) cannot be told from the source file: not imported"),
    ("Op.37", "All-Night Vigil (Vespers)", 1915, IN, r"vespers|all night vigil|bogoroditse|ave maria", "Jurgenson 1915; 'Bogoroditse Devo' is no. 6"),
    ("Op.39", "Études-tableaux", 1917, IN, r"etudes? tableaux|etude tableau", "Gutheil/Muzgiz 1917"),
    ("Op.40", "Piano Concerto No. 4 in G minor", 1928, UNV, r"piano concerto (no )?4|concerto n4", "1928 / revised 1936 / 1941 editions cannot be told apart: not imported"),
    ("Op.41", "Three Russian Songs", 1927, IN, r"three russian songs", ""),
    ("Op.43", "Rhapsody on a Theme of Paganini", 1934, POST, r"paganini", "Published 1934"),
    ("Op.42", "Variations on a Theme of Corelli", 1931, POST, r"corelli", "Published 1931"),
    ("Op.44", "Symphony No. 3", 1937, POST, r"symphony (no )?3", "Published 1937"),
    ("Op.45", "Symphonic Dances", 1941, POST, r"symphonic dances", "Published 1941"),
    ("Op.13", "Symphony No. 1 in D minor", 1947, POST, r"symphony (no )?1", "First published posthumously 1947"),
    ("no Op.", "Polka italienne (Italian Polka)", 1906, UNV, r"italian polka|polka italienne|italian polkka", "Arrangement of a Rubinstein/Italian tune; pub. date not confirmed"),
]

COMPOSERS = {
    "ravel": {
        "name": "Maurice Ravel", "canon": "maurice ravel", "death": 1937, "birth": 1875,
        "catalogue": "Marnat M. (1-86, A-series arrangements)", "rows": RAVEL,
        "prefix": "ravel", "genre": "classical", "era": "Impressionist",
        "scope_note": "Principal published works; early juvenilia, Conservatoire fugues and Prix de Rome cantatas are grouped.",
    },
    "strauss_r": {
        "name": "Richard Strauss", "canon": "richard strauss", "death": 1949, "birth": 1864,
        "catalogue": "Op. / TrV (Trenner)", "rows": STRAUSS,
        "prefix": "rstrauss", "genre": "classical", "era": "Late Romantic",
        "scope_note": "Principal works only (about 40 of 90 Op. numbers + selected TrV works); not the full ~300-entry TrV.",
    },
    "elgar": {
        "name": "Edward Elgar", "canon": "edward elgar", "death": 1934, "birth": 1857,
        "catalogue": "Op. (no standard thematic catalogue)", "rows": ELGAR,
        "prefix": "elgar", "genre": "classical", "era": "Late Romantic",
        "scope_note": "Principal published works; minor part-songs and piano miniatures not listed.",
    },
    "holst": {
        "name": "Gustav Holst", "canon": "gustav holst", "death": 1934, "birth": 1874,
        "catalogue": "Op. / H. (Imogen Holst)", "rows": HOLST,
        "prefix": "holst", "genre": "classical", "era": "20th century",
        "scope_note": "Principal works; Op./H. numbers checked against the Wikipedia work list (Imogen Holst H. catalogue) for the orchestral/band/choral entries.",
    },
    "rachmaninoff": {
        "name": "Sergei Rachmaninoff", "canon": "sergei rachmaninoff", "death": 1943, "birth": 1873,
        "catalogue": "Op. (Threlfall)", "rows": RACHMANINOFF,
        "prefix": "rachmaninoff", "genre": "classical", "era": "Late Romantic",
        "scope_note": "Principal works by opus; the many songs (Op.4, 8, 14, 21, 26, 34, 38) are covered by only a few entries.",
    },
}
